version: '3'
services:
  web:
    image: bakaframework/php56-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/app:/app/
      - ${PWD}/logs:/var/log/apache2/
    networks:
      - outside
    restart: always


networks:
  outside:
    driver: "bridge"